[DEFAULT]
# Default ban: 1 hour
bantime = 3600
# Window untuk hitung failures: 10 menit
findtime = 600
# Default 5 failures = ban
maxretry = 5
# Backend
backend = auto
# Action: pakai iptables
banaction = iptables-multiport

[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 86400
findtime = 600

[smart-lms-login]
enabled = true
port = 3008
filter = smart-lms-login
logpath = /var/log/nginx/access.log
maxretry = 5
findtime = 300
bantime = 1800

[nginx-ratelimit-spam]
enabled = true
port = 3008,80,443,3002,3005,8082,8085
filter = nginx-ratelimit-spam
logpath = /var/log/nginx/access.log
maxretry = 20
findtime = 60
bantime = 3600

[nginx-limit-req]
enabled = true
port = 3008,80,443,3002,3005,8082,8085
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 60
bantime = 1800

[nginx-scanner]
enabled = true
port = 80,443,3002,3005,3008,8082,8085
filter = nginx-scanner
logpath = /var/log/nginx/access.log
maxretry = 3
findtime = 600
bantime = 86400
